"""
Stretch feature evaluation — semantic vs. hybrid (semantic + BM25) retrieval.

Runs the 5 evaluation questions through both retrieval modes and writes a side-by-side
comparison (eval_hybrid_comparison.md): retrieved sources, whether the key regulation
chunks appear, and the resulting answer for each mode. Also runs two "probe" queries that
use regulation vocabulary, to show when hybrid's keyword matching actually helps.

Run:  python evaluate_hybrid.py
"""

from pathlib import Path

from evaluate import EVAL
from query import ask

OUT = Path("eval_hybrid_comparison.md")

# Chunks that actually contain the §61.87 pre-solo requirements (ground truth for Q4).
Q4_TARGET_CHUNKS = {475, 476}

PROBES = [
    "What does 14 CFR 61.87 require for pre-solo flight training?",
    "pre-solo knowledge test and flight training requirements student pilot",
]


def _sources(hits):
    return list(dict.fromkeys(h["source"] for h in hits))


def _has_part61_solo(hits):
    return any(
        h["source"].startswith("14-CFR-Part-61") and h["chunk_index"] in Q4_TARGET_CHUNKS
        for h in hits
    )


def main():
    lines = ["# Hybrid vs. Semantic Retrieval — Comparison\n",
             "Generated by `evaluate_hybrid.py`. k=4 for both modes; hybrid = "
             "Reciprocal Rank Fusion of semantic (cosine) and BM25 keyword search.\n"]

    for i, item in enumerate(EVAL, 1):
        q = item["q"]
        sem = ask(q, mode="semantic")
        hyb = ask(q, mode="hybrid")
        lines.append(f"\n## Q{i}. {q}\n")
        lines.append(f"**Expected:** {item['expected']}\n")
        lines.append(f"- **Semantic sources:** {', '.join(_sources(sem['hits']))}")
        lines.append(f"- **Hybrid sources:** {', '.join(_sources(hyb['hits']))}\n")
        lines.append(f"**Semantic answer:** {sem['answer']}\n")
        lines.append(f"**Hybrid answer:** {hyb['answer']}\n")
        if i == 4:
            lines.append(f"_§61.87 chunk retrieved? semantic={_has_part61_solo(sem['hits'])}, "
                         f"hybrid={_has_part61_solo(hyb['hits'])}_\n")
        print(f"Q{i}: sem_sources={len(_sources(sem['hits']))} "
              f"hyb_sources={len(_sources(hyb['hits']))}"
              + (f"  [Q4 §61.87 sem={_has_part61_solo(sem['hits'])} "
                 f"hyb={_has_part61_solo(hyb['hits'])}]" if i == 4 else ""))

    lines.append("\n## Probe queries (regulation vocabulary)\n")
    lines.append("These use the regulation's own terms to show when hybrid's keyword "
                 "matching helps.\n")
    for p in PROBES:
        sem = ask(p, mode="semantic")
        hyb = ask(p, mode="hybrid")
        lines.append(f"\n**Probe:** {p}\n")
        lines.append(f"- semantic §61.87 chunk retrieved: {_has_part61_solo(sem['hits'])}; "
                     f"sources: {', '.join(_sources(sem['hits']))}")
        lines.append(f"- hybrid §61.87 chunk retrieved: {_has_part61_solo(hyb['hits'])}; "
                     f"sources: {', '.join(_sources(hyb['hits']))}")
        print(f"Probe '{p[:40]}...': sem61.87={_has_part61_solo(sem['hits'])} "
              f"hyb61.87={_has_part61_solo(hyb['hits'])}")

    OUT.write_text("\n".join(lines))
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()
